version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: game
    volumes:
      - ../data:/var/lib/postgresql/data
    ports:
      - 5432:5432